### ISSUE TITLE
[2pt] Milestone 1: Login page and registration page

### ISSUE THREAD

**Issue by prg-04** [prg-04/SavvyBite#2]
- [ ]  Can register a new user.
- [ ]  User logs in with a combination of email and password.
- [ ]  Hashed password should be stored in the database.
- [ ]  Ask for confirmation of email.
- [ ]  Can reset password.
